### ISSUE TITLE
[feature-request] Add number of unresolved threads also

### ISSUE THREAD

**Issue by dhlavaty** [soson/gitlab-merge-request-userscript#2]
There is Discussion API:

```
https://gitlab.com/api/v4/projects/{PROJECTID}/merge_requests/{MERGEREQUESTID}/discussions
``` 

If you filter out all `resolvable: true` notes, and then all `resolved: false` notes, you should be able to count number of unresolved threads. This will be very useful to be displayed on 'all merge request' page.

**Comment by soson** [comment]
fixed in #3
