### ISSUE TITLE
[feature request] Autodetect which GitLab is used

### ISSUE THREAD

**Issue by dhlavaty** [soson/gitlab-merge-request-userscript#4]
It would be nice, to autodetect which GitLab is used by the user. If it is GitLab-in-cloud ( gitlab.com domain ) or custom Gitlab-on-premise ( for example my-gitlab.some.subdomains.com domain ).

I guess, URL in user's browser can serve this purpose.

**Comment by soson** [comment]
released in version 0.0.3
